# Generated by Django 5.2.8 on 2025-12-03 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_managers_remove_restaurant_delivery_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='addons',
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Extra Cheese, Bacon, Avocado', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Additional price for this addon', max_digits=10)),
                ('restaurant', models.ForeignKey(help_text='Restaurant that offers this addon', on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='food',
            name='available_addons',
            field=models.ManyToManyField(blank=True, help_text='Select addons available for this food item', to='core.addon'),
        ),
    ]
