# Generated by Django 5.2.8 on 2025-12-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_food_addons_addon_food_available_addons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of this category', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='e.g., Pizza, Burger, Pasta, Salad', max_length=50, unique=True),
        ),
    ]
