# Generated by Django 5.2.8 on 2025-12-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_options_remove_category_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(help_text='Restaurant cuisine type or description (e.g., Italian, Fast Food, Asian Fusion)', max_length=255),
        ),
    ]
