# Generated by Django 5.2.8 on 2025-12-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Bangladesh phone number format: +880 1XXX-XXXXXX or 01XXX-XXXXXX', max_length=20, null=True),
        ),
    ]
