# Generated by Django 5.2.8 on 2025-12-11 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_food_is_available_food_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='food',
            name='stock_quantity',
        ),
    ]
