# Generated by Django 5.2.8 on 2025-12-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20251211_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether this item is currently available'),
        ),
        migrations.AddField(
            model_name='food',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Available quantity in stock'),
        ),
    ]
