# Generated by Django 5.2.8 on 2025-12-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_food_is_available_food_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Card'), ('mobile_banking', 'Mobile Banking (bKash)')], max_length=20),
        ),
    ]
