# Generated by Django 5.2.8 on 2025-12-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.JSONField(blank=True, help_text='Current location data when address is not saved', null=True),
        ),
    ]
