# Generated by Django 5.2.8 on 2025-12-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_order_delivery_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.TextField(blank=True, help_text='Restaurant address', null=True),
        ),
    ]
