# Generated by Django 5.2.8 on 2025-12-13 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_restaurant_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderchatmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order Chat Message', 'verbose_name_plural': 'Order Chat Messages'},
        ),
        migrations.AlterField(
            model_name='orderchatmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image attachment', null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='orderchatmessage',
            name='message',
            field=models.TextField(help_text='Message content'),
        ),
        migrations.AlterField(
            model_name='orderchatmessage',
            name='order',
            field=models.ForeignKey(help_text='Select the order this message belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
        migrations.AlterField(
            model_name='orderchatmessage',
            name='sender',
            field=models.ForeignKey(help_text='Who is sending this message', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
