# Generated by Django 5.2.8 on 2025-12-13 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_update_orderchatmessage_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, help_text='Total lifetime earnings', max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Available balance for withdrawal', max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Pending balance (not yet available)', max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount withdrawn', max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15.0, help_text='Platform commission percentage', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='core.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Earnings',
                'verbose_name_plural': 'Restaurant Earnings',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Withdrawal amount', max_digits=10)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_banking', 'Mobile Banking (bKash/Nagad)'), ('check', 'Check')], default='bank_transfer', max_length=20)),
                ('payment_details', models.JSONField(help_text='Bank account or mobile banking details')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes or rejection reason', null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='core.restaurant')),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
