# Generated by Django 5.2.8 on 2025-12-24 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_earnings_and_withdrawals'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the login', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('success', models.BooleanField(default=True, help_text='Whether login was successful')),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for login failure', max_length=200, null=True)),
                ('session_key', models.CharField(blank=True, help_text='Django session key', max_length=40, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Log',
                'verbose_name_plural': 'Login Logs',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', '-login_time'], name='core_loginl_user_id_be9f15_idx'), models.Index(fields=['-login_time'], name='core_loginl_login_t_b307d8_idx'), models.Index(fields=['success'], name='core_loginl_success_0b884d_idx')],
            },
        ),
    ]
