# Generated by Django 5.2.8 on 2025-12-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, help_text='Estimated delivery time', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, help_text='When rider picked up the order', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prep_started_at',
            field=models.DateTimeField(blank=True, help_text='When preparation started', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prep_time_remaining',
            field=models.IntegerField(help_text='Remaining preparation time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_at',
            field=models.DateTimeField(blank=True, help_text='When food was marked ready', null=True),
        ),
        migrations.AddField(
            model_name='riderlocation',
            name='accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='riderlocation',
            name='heading',
            field=models.FloatField(blank=True, help_text='Direction in degrees (0-360)', null=True),
        ),
        migrations.AddField(
            model_name='riderlocation',
            name='is_moving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderlocation',
            name='speed',
            field=models.FloatField(blank=True, help_text='Speed in km/h', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='eta',
            field=models.CharField(help_text="Estimated time of arrival (e.g., '15 min')", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='prep_time',
            field=models.IntegerField(help_text='Estimated preparation time in minutes', null=True),
        ),
    ]
