# Generated by Django 5.2.8 on 2025-12-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order_estimated_delivery_time_order_picked_up_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address_line',
            field=models.TextField(default='Address not set', help_text='Full address line'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_title',
            field=models.CharField(default='Restaurant Location', help_text="Address title (e.g., 'Main Branch', 'Downtown Location')", max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='area',
            field=models.CharField(blank=True, help_text='Area/Neighborhood', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='Dhaka', help_text='City', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal/ZIP code', max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(blank=True, help_text='Legacy address field (deprecated)', null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(default=23.8103, help_text='Latitude coordinate'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='lng',
            field=models.FloatField(default=90.4125, help_text='Longitude coordinate'),
        ),
    ]
